swagger: "2.0"
info:
  description: "It's cool, I know"
  version: "6.9.69"
  title: "Riley's Magnificent Movie API"
schemes:
- "http"
tags:
  - name: "Movies"
paths:
  /generated/issues:
    get:
      tags:
      - "Movies"
      summary: "Get ALL the movies"
      description: "'Get All the movies' but in the description"
      operationId: "getMovies"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Movie"
        "500":
          description: "Internal server error"
  /generated/issues/{id}:
    get:
      tags:
      - "Movies"
      summary: "Get one of the movies using an ID"
      description: "'Get one of the movies using an ID' but in the description"
      operationId: "getMovieById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of movie that needs to be fetched"
        required: true
        type: "integer"
        maximum: 10.0
        minimum: 1.0
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Movie"
        "500":
          description: "Movie not found"
definitions:
  Movie:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      description:
        type: "string"
      images:
        type: "object"
        properties:
          path:
            type: "string"
          extension:
            type: "string"
          pathIncludingExtension:
            type: "string"